### ISSUE TITLE
Multiple paths

### ISSUE THREAD

**Issue by jacob-j** [markogresak/cloud-ignore-files#1]
Hello!

Awesome script, works like a charm! Thank you for making this.
Is it possible to add multiple paths? If I run the script again, it will just change the path right?
For example, I have some projects in _/Projects_ but also in _/Clients_, so would want projects to be synced to _/cloud/projects_ and clients to _/cloud/clients_.

Of course I could just move them to a parent directory, but would be cool if its easy to implement :)

Kind regards

**Comment by markogresak** [comment]
Hi @jacob-j, if I'm not mistaken, unison supports only a single path ([docs, see "Preferences" section](https://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html)). 

You could set up two separate scripts, one takes care of `/Projects <->  /cloud/projects` and the second one to handle `/Clients <->  /cloud/clients`. This can be done easily by modifying [`local_path`](https://github.com/markogresak/cloud-ignore-files/blob/master/install.sh#L12), [`cloud_path`](https://github.com/markogresak/cloud-ignore-files/blob/master/install.sh#L18) and [`label`](https://github.com/markogresak/cloud-ignore-files/blob/master/install.sh#L34) values inside the install script. I tried to write helpful comments, but I'll explain it again just to be sure:
 - `local_path`: path where you want to copy from, e.g. `/Projects`
 - `cloud_path`: path where you want to copy to, e.g. `/cloud/projects`
 - `label`: identifier of the, i.e. script/service name. **It's important to change this** or the first script will be overridden when you try to install the second one. Also, keep in mind to change the label accordingly if you use `--uninstall` feature. 

I know this solution is not ideal, but I hope it's good enough. Let me know if that works for you.

**Comment by jacob-j** [comment]
Hello @markogresak.
Thank you for quick reply :)

Cool, that sounds good. Thought the label were some protection for Apple Developer validation or similar. I will rename it for my different directories.
That solution will work fine!

Thanks again!

**Comment by markogresak** [comment]
I don't think the label really matters. I used the name to match the naming conventions of other `launchd` configs. 

If you take look at [Creating Launch Daemons and Agents - Creating a launchd Property List File](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html#//apple_ref/doc/uid/10000172i-SW7-104142-BCICCCFI), you can see that there is no limitations about the label value, other than it being unique. I would suggest following a template `com.[username].[some_name]` to follow the `launchd` config naming convention and make sure you're using a unique config name.
