### ISSUE TITLE
context menu shortcut to selectively ignore folders

### ISSUE THREAD

**Issue by tsdexter** [markogresak/cloud-ignore-files#4]
Not sure if you still have issues with this but I found your project when trying to solve this issue for myself - I ended up making an Automator utility to achieve a similar result: https://github.com/tsdexter/iCloud-NoSync

and an npm package specific to node_modules: https://www.npmjs.com/package/icloud-nosync-node

**Comment by markogresak** [comment]
Thanks for sharing, added it to "Related solutions" section in the readme (f5949a43c846df4d248f0eb176c9ffc0951b4b74).
