### ISSUE TITLE
MacOS Catalina: Operation not permitted

### ISSUE THREAD

**Issue by bar2cha** [markogresak/cloud-ignore-files#5]
Hi,
thanks for great script, but in Catalina not working.

unisono.err.log
```
Unison 2.51.2 (ocaml 4.06.1): Contacting server...
Fatal error: Error in canonizing path:
Operation not permitted
```

**Comment by chrisblossom** [comment]
@bar2cha have you found a solution to this? I'm having the same problem.

**Comment by bar2cha** [comment]
@chrisblossom  I gave it up
take a look at tsdexter's recommendations in the [next issue](https://github.com/markogresak/cloud-ignore-files/issues/4)

**Comment by chrisblossom** [comment]
This can be fixed by adding `/bin/bash` to `System Preferences/Security & Privacy/Privacy/Full Disk Access`.

<img width="659" alt="Screen Shot 2021-02-01 at 3 45 59 PM" src="https://user-images.githubusercontent.com/1595871/106532234-a6c0cf00-64a4-11eb-9821-a7b5b34ce69d.png">

**Comment by markogresak** [comment]
@chrisblossom thanks for pointing out the permission problem, I have added a note about it to the readme: https://github.com/markogresak/cloud-ignore-files/blob/master/README.md#installing.
